#!/usr/bin/env bash
# Classic FizzBuzz Algorithm; Fizz when multiple of 3 and Buzz when multiple of 5 and FizzBuzz when a multiple of both, else display Number.

for ((i=1; i<=100; i++)); do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
