#!/usr/bin/env bash
# Bash script that prints Besat School 10 times, but displays Hi as well, on the 9th iteration

count=0

while [ "$count" -lt 10 ]; do
	if [ "$count" -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
