#!/usr/bin/env bash
# Bash script that loops from 1 - 10 displaying "Best School" except on the 4th "bad luck" and 8th "good luck" iterations

count=1

while [ "$count" -le 10 ]; do
	if [ "$count" -eq 4 ]; then
		echo "bad Luck"
	elif [ "$count" -eq 8 ]; then
		echo "good Luck"
	else
		echo "Best School"
	fi
	((count++))
done
