#!/usr/bin/env bash
# Displays numbers from 1 to 20 and: 
# (i) displays 4 and then bad luck from China for the 4th loop iteration
# (ii) displays 9 and then bad luck from Japan for the 9th loop iteration
# (iii) displays 17 and then bad luck from Italy for the 17th loop iteration

# Must Use:
# You must use the while loop (for and until are forbidden)
# You must use the case statement

count=1

while [ "$count" -le 20 ]; do
	case $count in
		4)
			echo "$count"
			echo "bad luck from China"
			;;
		9)
			echo "$count"
			echo "bad luck from Japan"
			;;
		17)
			echo "$count"
			echo "bad luck from Italy"
			;;
		*)
			echo "$count"
			;;
	esac
	((count++))
done
