#!/usr/bin/env bash
# Bash script that displays content of current directory in list format excluding hidden files and the first '-' in the name

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
